name: Upload Website

on:
  push:
    branches:
    - main

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
       
    - name: Zip Folder
      run: zip -r release.zip . -x ".git/*" ".github/*"
    - name: Release to Github
      run: echo "Release"
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
          name: release
          path: release.zip
    - name: Upload to S3 as artifact
      uses: medlypharmacy/s3-artifacts-action@master
      with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket_name: "githubactionpoc"
          source_path: 'release.zip'
   
