name: Upload Website

on:
  push:
    branches:
    - main

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Zip Folder
      run: zip -r release.zip . -x ".git/*" ".github/*"
      
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
          name: release
          path: release.zip
                    
    - name: Upload to S3 as artifact
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: "githubactionpoc"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
       
      
      
    - name: Create CodeDeploy Deployment test
      id: deployfroms3test
      run: |
          aws deploy create-deployment  \
          --application-name testactions    --deployment-group development  \
          --s3-location bucket=githubactionpoc,bundleType=zip,key=release.zip
        
        
        
        
